[package]
name = "advent-of-code-2022-05a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2022, problem 05a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["stack"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.11.0"
