[package]
name = "advent-of-code-2018-01a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2018, problem 01a"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
