[package]
name = "advent-of-code-2021-15a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 15a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["graph-theory", "shortest-path"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
