[package]
name = "advent-of-code-2022-11b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2022, problem 11b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["divisibility", "interpreter", "modular-arithmetic"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
