[package]
name = "advent-of-code-2019-07b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2019, problem 07b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["intcode", "optimization"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.11.0"

[dev-dependencies]
rstest = { version = "0.18.2", default-features = false }
