[package]
name = "advent-of-code-2020-08a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 08a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["interpreter", "pseudo-assembly"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
