[package]
name = "advent-of-code-2018-23a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2018, problem 23a"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
