[package]
name = "advent-of-code-2016-01a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 01a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["grid-movement", "taxicab-metric"]

[dependencies]
adventutil = { path = "../../adventutil" }

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
