[package]
name = "advent-of-code-2019-11b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2019, problem 11b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["graphical-output", "intcode"]

[dependencies]
adventutil = { path = "../../adventutil", features = ["ocr"] }

[lints]
workspace = true
