[package]
name = "advent-of-code-2020-02b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 02b"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
