[package]
name = "advent-of-code-2020-17b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 17b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["game-of-life"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.14.0"

[lints]
workspace = true
