[package]
name = "advent-of-code-2023-16a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2023, problem 16a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["grid-movement"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
