[package]
name = "advent-of-code-2021-05b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 05b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["grid-movement"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
