[package]
name = "advent-of-code-2016-16b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 16b"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
