[package]
name = "advent-of-code-2015-19a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2015, problem 19a"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
