[package]
name = "advent-of-code-2016-21a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 21a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["interpreter"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
