[package]
name = "advent-of-code-2020-14b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 14b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["binary", "interpreter"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
