[package]
name = "advent-of-code-2023-01b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2023, problem 01b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.14.0"

[lints]
workspace = true

[dev-dependencies]
rstest = { version = "0.24.0", default-features = false }
