[package]
name = "advent-of-code-2020-19a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 19a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["regular-grammar"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
