[package]
name = "advent-of-code-2020-13a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 13a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["divisibility"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
