[package]
name = "advent-of-code-2023-05a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2023, problem 05a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true

[dev-dependencies]
rstest = { version = "0.21.0", default-features = false }
