[package]
name = "advent-of-code-2021-16a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 16a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["recursive-parse", "tree"]

[dependencies]
adventutil = { path = "../../adventutil" }

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
