[package]
name = "advent-of-code-2017-07b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 07b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["directed-acyclic-graph", "recursion"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
