[package]
name = "advent-of-code-2018-15a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2018, problem 15a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["grid-movement", "optimization", "shortest-path"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
