[package]
name = "advent-of-code-2024-19a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2024, problem 19a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["dynamic-programming"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
