[package]
name = "advent-of-code-2021-04b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 04b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["bingo"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
