[package]
name = "advent-of-code-2022-11a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2022, problem 11a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["divisibility", "interpreter"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
