[package]
name = "advent-of-code-2022-12b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2022, problem 12b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["graph-theory", "shortest-path"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
