[package]
name = "advent-of-code-2020-06a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 06a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["set-union"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
