[package]
name = "advent-of-code-2016-18b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 18b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["cellular-automata"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
