[package]
name = "advent-of-code-2022-03b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2022, problem 03b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["set-intersection"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
