[package]
name = "advent-of-code-2017-06b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 06b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["cycles"]

[dependencies]
adventutil = { path = "../../adventutil" }

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
