[package]
name = "advent-of-code-2017-13a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 13a"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
