[package]
name = "advent-of-code-2022-13a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2022, problem 13a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["recursive-parse"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.14.0"
thiserror = "2.0.0"

[dev-dependencies]
rstest = { version = "0.23.0", default-features = false }

[lints]
workspace = true
