[package]
name = "advent-of-code-2022-13a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2022, problem 13a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["recursive-parse"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.11.0"
thiserror = "1.0.40"

[dev-dependencies]
rstest = { version = "0.18.2", default-features = false }
