[package]
name = "advent-of-code-2021-01b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 01b"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
