[package]
name = "advent-of-code-2016-20a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 20a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["contiguous-ranges"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
