[package]
name = "advent-of-code-2021-07b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 07b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["optimization"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.12.0"

[lints]
workspace = true
