[package]
name = "advent-of-code-2024-03a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2024, problem 03a"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
