[package]
name = "advent-of-code-2021-09b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 09b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["graph-theory", "transitive-closure"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
