[package]
name = "advent-of-code-2023-10a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2023, problem 10a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["grid-movement"]

[dependencies]
adventutil = { path = "../../adventutil" }
thiserror.workspace = true

[lints]
workspace = true
