[package]
name = "advent-of-code-2016-13b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 13b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["transitive-closure"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
