[package]
name = "advent-of-code-2015-21a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2015, problem 21a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["optimization"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.14.0"

[lints]
workspace = true
