[package]
name = "advent-of-code-2020-12b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 12b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["grid-movement", "taxicab-metric"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
