[package]
name = "advent-of-code-2016-02b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 02b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["grid-movement"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
