[package]
name = "advent-of-code-2023-15a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2023, problem 15a"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
