[package]
name = "advent-of-code-2021-13b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 13b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["graphical-output"]

[dependencies]
adventutil = { path = "../../adventutil", features = ["ocr"] }
itertools = "0.11.0"
