[package]
name = "advent-of-code-2021-13b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 13b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["graphical-output"]

[dependencies]
adventutil = { path = "../../adventutil", features = ["ocr"] }
itertools.workspace = true

[lints]
workspace = true
