[package]
name = "advent-of-code-2021-14a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 14a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["most-common"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
