[package]
name = "advent-of-code-2020-07a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 07a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["transitive-closure", "tree"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
