[package]
name = "advent-of-code-2020-05b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 05b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["binary-search"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.12.1"

[lints]
workspace = true
