[package]
name = "advent-of-code-2021-10a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 10a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["balanced-brackets"]

[dependencies]
adventutil = { path = "../../adventutil" }

[dev-dependencies]
rstest = { version = "0.23.0", default-features = false }

[lints]
workspace = true
