[package]
name = "advent-of-code-2019-02b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2019, problem 02b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["intcode"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
