[package]
name = "advent-of-code-2022-13b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2022, problem 13b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["recursive-parse"]

[dependencies]
adventutil = { path = "../../adventutil" }
thiserror.workspace = true

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
