[package]
name = "advent-of-code-2022-13b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2022, problem 13b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["recursive-parse"]

[dependencies]
adventutil = { path = "../../adventutil" }
thiserror = "1.0.40"

[dev-dependencies]
rstest = { version = "0.22.0", default-features = false }

[lints]
workspace = true
