[package]
name = "advent-of-code-2024-07b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2024, problem 07b"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
