[package]
name = "advent-of-code-2016-24a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 24a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["maze", "optimization", "shortest-path", "travelling-salesman"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.14.0"

[lints]
workspace = true
