[package]
name = "advent-of-code-2017-14b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 14b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["connected-components"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
