[package]
name = "advent-of-code-2021-06b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 06b"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
