[package]
name = "advent-of-code-2020-10a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 10a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["graph-theory", "graph-traversal"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
