[package]
name = "advent-of-code-2022-07a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2022, problem 07a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["transitive-closure", "tree"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
