[package]
name = "advent-of-code-2019-07a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2019, problem 07a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["intcode", "optimization"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
