[package]
name = "advent-of-code-2016-04b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 04b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["Caesar-cipher"]

[dependencies]
adventutil = { path = "../../adventutil" }

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
