[package]
name = "advent-of-code-2016-04b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 04b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["Caesar-cipher"]

[dependencies]
adventutil = { path = "../../adventutil" }

[dev-dependencies]
rstest = { version = "0.24.0", default-features = false }

[lints]
workspace = true
