[package]
name = "advent-of-code-2023-15b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2023, problem 15b"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
thiserror.workspace = true

[lints]
workspace = true
