[package]
name = "advent-of-code-2018-16b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2018, problem 16b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["interpreter"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
