[package]
name = "advent-of-code-2020-03a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 03a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["grid-movement"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
