[package]
name = "advent-of-code-2018-04b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2018, problem 04b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["most-common"]

[dependencies]
adventutil = { path = "../../adventutil" }
