[package]
name = "advent-of-code-2017-16b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 16b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["permutations"]

[dependencies]
adventutil = { path = "../../adventutil" }
thiserror.workspace = true

[lints]
workspace = true
