[package]
name = "advent-of-code-2023-07b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2023, problem 07b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true
thiserror.workspace = true

[lints]
workspace = true
