[package]
name = "advent-of-code-2017-21a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 21a"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
thiserror.workspace = true

[lints]
workspace = true
