[package]
name = "advent-of-code-2020-11b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 11b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["cellular-automata", "vectors"]

[dependencies]
adventutil = { path = "../../adventutil" }
