[package]
name = "advent-of-code-2020-11b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 11b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["cellular-automata", "vectors"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
