[package]
name = "advent-of-code-2018-02b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2018, problem 02b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["Hamming-distance"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
