[package]
name = "advent-of-code-2018-11a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2018, problem 11a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.10.5"

[dev-dependencies]
rstest = { version = "0.16.0", default-features = false }
