[package]
name = "advent-of-code-2017-22a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 22a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["grid-movement"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
