[package]
name = "advent-of-code-2023-06a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2023, problem 06a"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
