[package]
name = "advent-of-code-2020-13b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 13b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["Chinese-remainder-theorem", "modular-arithmetic"]

[dependencies]
adventutil = { path = "../../adventutil" }

[dev-dependencies]
rstest = { version = "0.21.0", default-features = false }

[lints]
workspace = true
