[package]
name = "advent-of-code-2021-05a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 05a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["grid-movement"]

[dependencies]
adventutil = { path = "../../adventutil" }
either = "1.8.1"
