[package]
name = "advent-of-code-2024-13b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2024, problem 13b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["linear-diophantine-equations"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
