[package]
name = "advent-of-code-2017-03b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 03b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["number-spiral"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
