[package]
name = "advent-of-code-2016-06a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 06a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["most-common"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
