[package]
name = "gen"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution package generator"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.70"
fs-err = "2.9.0"
serde = { version = "1.0.164", features = ["derive"] }
tinytemplate = "1.2.1"

[lints]
workspace = true
