[package]
name = "advent-of-code-2017-11b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 11b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["grid-movement", "hex-grid"]

[dependencies]
adventutil = { path = "../../adventutil" }
thiserror.workspace = true

[lints]
workspace = true
