[package]
name = "advent-of-code-2017-07a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 07a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["directed-acyclic-graph", "recursion"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
