[package]
name = "advent-of-code-2016-05b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 05b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["md5"]

[dependencies]
adventutil = { path = "../../adventutil" }
hex.workspace = true
md-5.workspace = true

[lints]
workspace = true
