[package]
name = "advent-of-code-2017-19a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 19a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["maze", "grid-movement"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
