[package]
name = "advent-of-code-2020-05a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 05a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["binary-search"]

[dependencies]
adventutil = { path = "../../adventutil" }

[dev-dependencies]
rstest = { version = "0.24.0", default-features = false }

[lints]
workspace = true
