[package]
name = "advent-of-code-2020-10b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2020, problem 10b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["dynamic-programming", "graph-theory", "graph-traversal", "permutations"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
