[package]
name = "advent-of-code-2024-15a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2024, problem 15a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["grid-movement"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true
thiserror.workspace = true

[lints]
workspace = true
