[package]
name = "advent-of-code-2018-20a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2018, problem 20a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["grid-movement", "graph-theory", "shortest-path"]

[dependencies]
adventutil = { path = "../../adventutil" }

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
