[package]
name = "advent-of-code-2016-13a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 13a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["shortest-path"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
