[package]
name = "advent-of-code-2017-13b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2017, problem 13b"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
