[package]
name = "advent-of-code-2021-24a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 24a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
thiserror = "1.0.37"

[dev-dependencies]
rstest = { version = "0.15.0", default-features = false }
