[package]
name = "advent-of-code-2021-25a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 25a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["grid-movement"]

[dependencies]
adventutil = { path = "../../adventutil" }
thiserror = "1.0.40"

[lints]
workspace = true
