[package]
name = "advent-of-code-2024-23a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2024, problem 23a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["graph-theory", "complete-graphs"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
