[package]
name = "advent-of-code-2021-12b"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 12b"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["graph-theory", "graph-traversal"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools = "0.11.0"
