[package]
name = "advent-of-code-2016-12b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 12b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["interpreter", "pseudo-assembly"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
