[package]
name = "advent-of-code-2021-02a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 02a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["interpreter"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
