[package]
name = "advent-of-code-2022-15b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2022, problem 15b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["taxicab-metric"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
