[package]
name = "advent-of-code-2016-10a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2016, problem 10a"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
